// ============================================================
// RAMAYANA - Eternal Wisdom for Modern Life
// Created by Varaang Sharma
// Contact: varaangsharma@gmail.com
// Purpose: To make the timeless wisdom of Ramayana accessible
// to modern readers and help them find motivation in their daily lives.
// ============================================================

const storyData = [
    // ============================================================
    // CHAPTER 1: Bal Kanda - The Birth of Purpose
    // ============================================================
    {
        id: 1,
        title: "Bal Kanda - The Birth of Purpose",
        image: "ramayan-images/bal-kand-cover.jpg",
        setting: "Have you ever looked at your life and wondered if you were meant for something more? That quiet voice inside you that whispers, 'You are here for a reason'—what if that voice is telling the truth?",
        en: "In the magnificent city of Ayodhya, where golden spires touched the clouds and rivers flowed like liquid silver, King Dasharath ruled with a heart full of justice. But behind the grandeur of his palace, there was an emptiness that no treasure could fill. He had everything except a child. Night after night, he would stand on his balcony, looking at the stars, and ask the universe one question: 'Will my legacy live on?' He performed great sacrifices, he prayed with all his heart, and he never lost faith. Then one day, the heavens answered. Four sons were born to him—and the eldest was unlike any child ever born. His name was Ram. From the moment he took his first breath, something shifted in the cosmos. Sages who could see the future wept with joy. Ordinary people who held him felt a peace they had never known. He was not just a prince. He was a promise—a living, breathing promise that goodness would never disappear from this earth. As Ram grew, he did something remarkable. He did not rely on his royal birth. He studied harder than anyone. He trained longer than anyone. He served his parents with devotion that made even the gods admire him. He treated the poorest beggar with the same respect he showed the richest king. The strongest warrior? That was Ram. The wisest scholar? That was Ram. The kindest soul? That was Ram. He had every reason to be arrogant, but he chose humility. He had every reason to be lazy, but he chose discipline. He had every reason to be selfish, but he chose service. And that is what made him extraordinary—not the throne he was born into, but the man he chose to become.",
        hi: "अयोध्या की उस स्वर्णिम नगरी में, जहाँ सोने की कलशें बादलों को छूती थीं और नदियाँ चाँदी की तरह बहती थीं, राजा दशरथ न्यायपूर्ण हृदय से राज्य करते थे। लेकिन उनके महल की भव्यता के पीछे एक खालीपन था जिसे कोई खजाना नहीं भर सकता था। उनके पास सब कुछ था—एक संतान के अलावा। रात-रात भर वे अपनी बालकनी पर खड़े होकर तारों को देखते और ब्रह्मांड से एक ही प्रश्न पूछते: 'क्या मेरी विरासत जीवित रहेगी?' उन्होंने महान यज्ञ किए, पूरे मन से प्रार्थना की, और कभी आस्था नहीं खोई। फिर एक दिन आकाश ने उत्तर दिया। उन्हें चार पुत्रों का आशीर्वाद मिला—और सबसे बड़ा ऐसा बालक था जो कभी पैदा नहीं हुआ था। उसका नाम था राम। जिस क्षण उन्होंने पहली साँस ली, ब्रह्मांड में कुछ बदल गया। भविष्य देखने वाले ऋषि खुशी से रो पड़े। सामान्य लोग जो उन्हें गोद में लेते, उन्हें एक अनोखी शांति का अनुभव होता। वह केवल एक राजकुमार नहीं थे। वह एक वादा थे—एक जीवंत, साँस लेता वादा कि अच्छाई इस धरती से कभी गायब नहीं होगी। जैसे-जैसे राम बड़े हुए, उन्होंने कुछ अद्भुत किया। उन्होंने अपने राजसी जन्म पर भरोसा नहीं किया। उन्होंने किसी से अधिक मेहनत से पढ़ाई की। किसी से अधिक कठिन अभ्यास किया। अपने माता-पिता की ऐसी सेवा की कि देवता भी उनकी प्रशंसा करते थे। सबसे गरीब भिखारी के साथ वही सम्मान से पेश आते जो सबसे अमीर राजा के साथ। सबसे शक्तिशाली योद्धा? वह थे राम। सबसे बुद्धिमान विद्वान? वह थे राम। सबसे दयालु आत्मा? वह थे राम। उनके पास अहंकारी होने के सभी कारण थे, लेकिन उन्होंने विनम्रता चुनी। उनके पास आलसी होने के सभी कारण थे, लेकिन उन्होंने अनुशासन चुना। उनके पास स्वार्थी होने के सभी कारण थे, लेकिन उन्होंने सेवा चुनी। और यही बात उन्हें असाधारण बनाती है—वह सिंहासन नहीं जिस पर वह पैदा हुए, बल्कि वह व्यक्ति जो उन्होंने बनना चुना।",
        sa: "तस्याम् स्वर्णिमायाम् अयोध्यायाम्, यत्र सुवर्णकलशाः मेघान् स्पृशन्ति स्म, नद्यः च रजतवत् प्रवहन्ति स्म, राजा दशरथः न्यायेन हृदयेन राज्यम् अकरोत्। किन्तु तस्य महलस्य वैभवस्य पृष्ठे एकः रिक्तता आसीत् याम् कोशः न पूरयितुम् शक्नोति। तस्य सर्वम् आसीत्—पुत्रं विना। रात्रौ रात्रौ सः स्वबाल्कनीम् गत्वा तारकाः दृष्ट्वा ब्रह्माण्डम् एकम् प्रश्नम् अपृच्छत्: 'किं मम वंशः जीविष्यति?' सः महायज्ञानि अकरोत्, पूर्णहृदयेन प्रार्थितवान्, कदापि श्रद्धाम् न अत्यजत्। तदा एकस्मिन् दिने द्यौः उत्तरम् अददात्। चत्वारः पुत्राः जाताः—ज्येष्ठः अन्यः बालकः आसीत् यः कदापि न जातः। तस्य नाम रामः आसीत्। यस्मिन् क्षणे सः प्रथमम् श्वासम् अगृह्णात्, ब्रह्माण्डे किमपि परिवर्तितम्। भविष्यदर्शिनः ऋषयः आनन्देन अरोदन्। सामान्याः जनाः ये तम् अङ्के धारयन्ति स्म, ते एकाम् अनन्याम् शान्तिम् अनुभवन्ति स्म। सः केवलम् राजकुमारः न आसीत्; सः प्रतिज्ञा आसीत्—जीवन्ती, श्वसन्ती प्रतिज्ञा यत् धर्मः अस्मात् पृथिव्याम् कदापि न गमिष्यति। वर्धमानः रामः अद्भुतम् अकरोत्। सः राजकीयजन्मनि न अविश्वसीत्। सः सर्वेषाम् अधिकम् अभ्यस्तवान्। सर्वेषाम् अधिकम् अभ्यासितवान्। मातापित्रोः सेवाम् अकरोत् येन देवाः अपि तम् अप्रशंसन्। निर्धनतमम् भिक्षुकम् तेनैव आदरेण अमन्यत येन धनिनम् राजानम्। बलवान् योद्धा? सः रामः। बुद्धिमान् पण्डितः? सः रामः। दयालुः आत्मा? सः रामः। तस्य अहङ्कारिणः भवितुम् सर्वे कारणानि आसन्, किन्तु सः विनम्रताम् अचिनोत्। तस्य आलसिनः भवितुम् सर्वे कारणानि आसन्, किन्तु सः अनुशासनम् अचिनोत्। तस्य स्वार्थिनः भवितुम् सर्वे कारणानि आसन्, किन्तु सः सेवाम् अचिनोत्। एतत् एव तम् असाधारणम् करोति—न सः सिंहासनः यस्मिन् सः जातः, अपितु सः पुरुषः यः सः भवितुम् अचिनोत्।",
        question: "What is the promise that you carry within you? That unique gift that only you can give to this world—are you nurturing it, or are you ignoring it?",
        answer: "Ram never waited for destiny to tap him on the shoulder. He never sat around wondering if he was special. He simply woke up every morning and decided to become the best version of himself. He studied when others slept. He served when others took. He gave when others grabbed. And slowly, quietly, he became extraordinary. He did not become great because he was born a prince. He became great because he lived like a king—not a king of palaces, but a king of his own mind, his own actions, and his own purpose.",
        takeaway: "Stop waiting for permission to be extraordinary. Your purpose is not something you find; it is something you build—one disciplined action, one kind word, one brave decision at a time. Start building today."
    },

    // ============================================================
    // CHAPTER 2: Bal Kanda - The Test of Character
    // ============================================================
    {
        id: 2,
        title: "Bal Kanda - The Test of Character",
        image: "ramayan-images/bow-breaking.jpg",
        setting: "When the moment of truth arrives and the whole world is watching, do you freeze or do you rise? Do you shrink into the shadows, or do you step into the light and show the world who you truly are?",
        en: "The journey of a hero never begins with comfort. It begins with a call to adventure. When Sage Vishwamitra arrived in Ayodhya seeking help, everyone hesitated. Demons were disrupting his sacred rituals—demons that no ordinary warrior could defeat. The mighty kings of the land had failed. The great warriors had retreated. But Ram, still just a teenager, stepped forward without a moment's hesitation. 'I will go,' he said. His voice was calm, but his eyes burned with purpose. And he did not just go—he conquered. He used his intelligence to outsmart the demons, not just his arrows. He used his wisdom to find solutions that brute force could never achieve. Years later, in the kingdom of Mithila, King Janak had a challenge for the world. A divine bow, so heavy that it had been moved by no man for generations, sat in his court. 'Whoever can lift and string this bow,' he declared, 'will marry my daughter, the radiant Sita.' Kings came. Kings tried. Kings failed. Some strained so hard they broke their arms. Others gave up before they even started. Then Ram walked forward. He was young. He was not the strongest king in the room. But he had something they lacked—quiet confidence. He did not show off. He did not grunt. He simply walked up to the bow, lifted it as if it weighed nothing, and strung it in one fluid motion. And then—CRACK—the bow shattered. The sound echoed across the kingdom. The court erupted in shock. Ram did not celebrate. He did not boast. He simply turned around, looked at Sita, and smiled. He had passed the test of character, not with arrogance, but with the quiet strength of a man who had prepared for this moment his entire life.",
        hi: "एक नायक की यात्रा आराम से कभी शुरू नहीं होती। यह शुरू होती है साहसिकता के आह्वान से। जब ऋषि विश्वामित्र अयोध्या पहुँचे और मदद माँगी, तो सभी हिचकिचाए। राक्षस उनके पवित्र यज्ञों को बाधित कर रहे थे—ऐसे राक्षस जिन्हें कोई साधारण योद्धा नहीं हरा सकता था। देश के शक्तिशाली राजा असफल हो चुके थे। महान योद्धा पीछे हट चुके थे। लेकिन राम, जो अभी भी एक किशोर थे, बिना एक क्षण की हिचकिचाहट के आगे बढ़े। 'मैं चलूँगा,' उन्होंने कहा। उनकी आवाज़ शांत थी, लेकिन उनकी आँखों में उद्देश्य की आग जल रही थी। और वह न केवल गए—उन्होंने जीत हासिल की। उन्होंने केवल अपने बाणों से नहीं, बल्कि अपनी बुद्धि से राक्षसों को मात दी। उन्होंने अपनी समझदारी से ऐसे समाधान निकाले जो क्रूर बल कभी नहीं पा सकता था। वर्षों बाद, मिथिला राज्य में, राजा जनक ने दुनिया के लिए एक चुनौती रखी। एक दिव्य धनुष, इतना भारी कि उसे पीढ़ियों से कोई नहीं उठा पाया था, उनके दरबार में रखा था। 'जो कोई भी इस धनुष को उठाकर चढ़ा सकेगा,' उन्होंने घोषणा की, 'वह मेरी पुत्री, ज्योतिर्मयी सीता से विवाह करेगा।' राजा आए। राजाओं ने प्रयास किया। राजा असफल रहे। कुछ ने इतना जोर लगाया कि उनकी बाहें टूट गईं। कुछ ने शुरू करने से पहले ही हार मान ली। फिर राम आगे बढ़े। वह युवा थे। वह कमरे में सबसे मजबूत राजा नहीं थे। लेकिन उनके पास वह था जो दूसरों में कमी थी—शांत आत्मविश्वास। उन्होंने दिखावा नहीं किया। उन्होंने कराहा नहीं। वह बस धनुष के पास गए, उसे ऐसे उठाया जैसे उसका कोई भार ही न हो, और एक ही प्रवाह में उसे चढ़ा दिया। और फिर—CRACK—धनुष टूट गया। आवाज़ पूरे राज्य में गूँजी। दरबार सदमे में आ गया। राम ने जश्न नहीं मनाया। उन्होंने शेखी नहीं बघारी। वह बस मुड़े, सीता को देखा, और मुस्कुराए। उन्होंने अहंकार से नहीं, बल्कि उस शांत शक्ति से चरित्र की परीक्षा पास की, जो एक ऐसे व्यक्ति की होती है जिसने अपने जीवन भर इस क्षण के लिए तैयारी की थी।",
        sa: "वीरस्य यात्रा कदापि सुखेन न आरभते। सा आरभते साहसिकतया। यदा विश्वामित्रः अयोध्याम् आगत्य साहाय्यम् अयाचत, सर्वे संशयितवन्तः। राक्षसाः तस्य पवित्राणि यज्ञानि विघ्नयन्ति स्म—राक्षसाः यान् सामान्यः योद्धा न पराजेतुम् शक्नोति। राज्यस्य शक्तिशालिनः राजानः असफलाः आसन्। महान्तः योद्धारः न्यवर्तन्त। किन्तु रामः, यः अद्यापि किशोरः आसीत्, संकोचम् विना अग्रसरः अभवत्। 'अहं गमिष्यामि,' सः अवदत्। तस्य वाणी शान्ता आसीत्, किन्तु तस्य नेत्रयोः उद्देश्याग्निः प्रज्वलितः आसीत्। सः केवलम् अगच्छत्—सः अजयत्। सः केवलम् बाणैः न, अपितु बुद्ध्या राक्षसान् पराजितवान्। सः प्रज्ञया तानि समाधानानि अविन्दत् यानि बलम् कदापि न अविन्दत्। वर्षाणि पश्चात्, मिथिलायाम्, राजा जनकः लोकाय एकम् आह्वानम् अकरोत्। दिव्यम् धनुः, अतीव गुरु यत् पीढीभिः कोऽपि न उत्थापितवान्, तस्य सभायाम् आसीत्। 'यः एतत् धनुः उत्थाप्य योजयेत्,' सः अघोषयत्, 'सः मम पुत्रीम् सीताम् वरिष्यति।' राजानः आगतवन्तः। राजानः प्रयत्नम् कृतवन्तः। राजानः असफलाः अभवन्। केचित् अतीव तनवन्त येन तेषाम् बाहवः भग्नाः। केचित् आरभणात् पूर्वम् एव हारम् अमन्यन्त। तदा रामः अग्रसरः अभवत्। सः युवा आसीत्। सः सभायाम् बलवान् राजा न आसीत्। किन्तु तस्य आसीत् यत् अन्येषाम् नासीत्—शान्तः आत्मविश्वासः। सः न प्रदर्शितवान्। सः न गर्जितवान्। सः केवलम् धनुः समीपम् गत्वा, भारम् विना इव उत्थाप्य, एकेन प्रवाहेन योजितवान्। ततः—CRACK—धनुः भग्नम् अभवत्। ध्वनिः सर्वे राज्ये प्रतिध्वनितः। सभा स्तब्धा अभवत्। रामः न उत्सवम् अकरोत्। न श्लाघितवान्। सः केवलम् परावृत्य, सीताम् दृष्ट्वा, स्मितम् अकरोत्। सः अहङ्कारेण न, अपितु तया शान्त्या शक्त्या चरित्रस्य परीक्षाम् उत्तीर्णवान् या तस्य मानवस्य भवति यः जीवनम् एतस्मै क्षणाय समर्पितवान्।",
        question: "What is the 'bow' in your life that you have been afraid to pick up? What opportunity are you avoiding because you doubt your own strength?",
        answer: "Ram did not wait to be invited. He did not wait to be recognized. He was not arrogant, but he also was not afraid. He had spent every single day of his life preparing for moments like this. He trained. He studied. He meditated. He served. And when the moment finally came, he did not hesitate. He did not need to prove anything to anyone because he had already proven everything to himself.",
        takeaway: "Opportunity does not knock on the door of the unprepared. Prepare yourself daily—train your mind, strengthen your body, nurture your soul. And when the moment comes, you will not rise to the occasion; you will simply be who you have always been."
    },

    // ============================================================
    // CHAPTER 3: Ayodhya Kanda - The Pain of Jealousy
    // ============================================================
    {
        id: 3,
        title: "Ayodhya Kanda - The Pain of Jealousy",
        image: "ramayan-images/kaikeyi-jealousy.jpg",
        setting: "Have you ever watched someone succeed and felt a sharp pang in your chest? That quiet whisper that says, 'Why them and not me?' That is jealousy—and it is the most dangerous poison you will ever drink.",
        en: "The news spread through Ayodhya like wildfire. Ram was going to be crowned king. The streets overflowed with celebrating people. Flowers rained from windows. Children danced in the streets. It was the happiest day the kingdom had ever seen. Everyone was smiling—except for one person. In the queen's chambers, Kaikeyi sat in silence. Her face was stone. Her heart was heavy. Her maid, Manthara, had been whispering in her ear for days. 'Do you see what is happening?' Manthara hissed. 'If Ram becomes king, your son Bharat will be nothing but a servant. He will bow to Ram. He will follow Ram's orders. Is that what you want for your son?' Kaikeyi wanted to ignore her. She loved Ram like her own son. But the poison had entered her heart. She could not sleep. She could not eat. All she could see was her son being humiliated. And in that moment of weakness, she made a decision that would break the kingdom apart. She used two boons that King Dasharath had given her years ago. She demanded two things: Bharat would be crowned king, and Ram would be exiled to the forest for fourteen years. The king collapsed in grief. The kingdom wept. But Ram—Ram simply accepted. He did not scream. He did not argue. He did not hate Kaikeyi. He looked at her with compassion and said, 'I understand. I will go.'",
        hi: "यह खबर अयोध्या में आग की तरह फैल गई। राम को राजा का ताज पहनाया जा रहा था। सड़कें जश्न मना रहे लोगों से भर गईं। खिड़कियों से फूल बरस रहे थे। बच्चे सड़कों पर नाच रहे थे। यह राज्य का सबसे खुशी का दिन था। सभी मुस्कुरा रहे थे—एक व्यक्ति को छोड़कर। रानी के कक्ष में, कैकेयी चुपचाप बैठी थीं। उनका चेहरा पत्थर जैसा था। उनका हृदय भारी था। उनकी दासी मंथरा दिनों से उनके कान में जहर घोल रही थी। 'क्या आप देख रही हैं क्या हो रहा है?' मंथरा ने फुसफुसाया। 'अगर राम राजा बन गए, तो आपका पुत्र भरत एक सेवक से अधिक कुछ नहीं होगा। वह राम के सामने झुकेगा। वह राम के आदेशों का पालन करेगा। क्या आप अपने पुत्र के लिए यही चाहती हैं?' कैकेयी उसे अनदेखा करना चाहती थीं। वह राम को अपने पुत्र की तरह प्यार करती थीं। लेकिन जहर उनके हृदय में प्रवेश कर चुका था। वह सो नहीं सकती थीं। खा नहीं सकती थीं। बस अपने पुत्र को अपमानित होते देख सकती थीं। और कमजोरी के उस क्षण में, उन्होंने एक निर्णय लिया जो पूरे राज्य को तोड़ देगा। उन्होंने दो वरदानों का उपयोग किया जो राजा दशरथ ने वर्षों पहले उन्हें दिए थे। उन्होंने दो माँगें रखीं: भरत राजा बने, और राम चौदह वर्षों के लिए वन में निर्वासित हो जाएँ। राजा दुःख से गिर पड़े। राज्य रो पड़ा। लेकिन राम—राम ने बस स्वीकार किया। उन्होंने चिल्लाया नहीं। उन्होंने बहस नहीं की। उन्होंने कैकेयी से घृणा नहीं की। उन्होंने करुणा के साथ उनकी ओर देखा और कहा, 'मैं समझता हूँ। मैं चला जाऊँगा।'",
        sa: "वार्ता अयोध्याम् अग्निवत् प्रसृता। रामः राजा अभिषेकः आसीत्। मार्गाः उत्सवकारिभिः जनैः परिपूर्णाः। गवाक्षेभ्यः पुष्पाणि वर्षन्ति स्म। बालकाः मार्गेषु नृत्यन्ति स्म। राज्यस्य सर्वाधिकम् आनन्दितम् दिनम् आसीत्। सर्वे स्मयन्ते स्म—एकं विना। रानीगृहे, कैकेयी मौनेन उपविष्टा आसीत्। तस्याः मुखम् पाषाणवत् आसीत्। तस्याः हृदयम् गुरु आसीत्। तस्याः दासी मंथरा दिनानि तस्याः कर्णे विषम् अस्यति स्म। 'पश्य किम् भवति?' मंथरा अशुश्रावयत्। 'यदि रामः राजा भवेत्, तव पुत्रः भरतः सेवकः भविष्यति। सः रामम् नमस्यति। सः रामस्य आज्ञाः पालयिष्यति। किं तव पुत्राय एतत् इच्छसि?' कैकेयी ताम् उपेक्षितुम् ऐच्छत्। सा रामम् पुत्रवत् अप्रियत्। किन्तु विषम् तस्याः हृदयम् प्रविष्टम्। सा न अशक्नोत् निद्रातुम्, न भोक्तुम्। केवलम् स्वपुत्रम् अपमान्यमानम् पश्यति स्म। तस्मिन् दुर्बलताक्षणे, सा निर्णयम् अकरोत् यत् राज्यम् भंक्ष्यति। सा द्वौ वरौ अयाचत यौ राजा दशरथः पूर्वम् अददात्। सा द्वे मागे अकरोत्: भरतः राजा भवेत्, रामः च चतुर्दश वर्षाणि वनम् गच्छेत्। राजा दुःखेन अपतत्। राज्यम् अरोदीत्। किन्तु रामः—रामः अंगीकृतवान्। न अचीत्करोत्। न विवादम् अकरोत्। न कैकेयीम् द्वेष्टि स्म। सः करुणया ताम् दृष्ट्वा अवदत्, 'अहम् जानामि। अहं गमिष्यामि।'",
        question: "Who or what is the 'Manthara' in your life? Who is poisoning your mind with comparison and making you feel like you are not enough?",
        answer: "Ram could have hated Kaikeyi. He had every right. She had just destroyed his future, his kingdom, his life. But he did not hate her. He understood her fear. He understood that her love for her son had been corrupted by a poisonous voice. He did not fight her. He did not curse her. He simply accepted what he could not change and walked away with dignity. He refused to carry anger in his heart because he knew that anger would hurt him far more than it would hurt her.",
        takeaway: "Jealousy is a poison that destroys the one who drinks it, not the one it is aimed at. Do not let comparison steal your peace. The success of others does not diminish your worth. Walk your own path with your head held high."
    },

    // ============================================================
    // CHAPTER 4: Ayodhya Kanda - The Graceful Exit
    // ============================================================
    {
        id: 4,
        title: "Ayodhya Kanda - The Graceful Exit",
        image: "ramayan-images/exile-forest.jpg",
        setting: "What happens when life pulls the rug out from under you? When everything you worked for, everything you loved, is suddenly taken away—do you crumble, or do you rise?",
        en: "The palace gates opened. Ram stepped out. He was wearing bark clothes—rough, itchy, nothing like the silk he had worn moments before. He had no chariot, no servants, no guards. Just his bare feet and a walking stick. Behind him walked Sita, his wife, who had refused to stay behind. 'Where my husband goes, that is my home,' she had said with quiet determination. Beside him walked Lakshman, his brother, who had sworn to protect him with his life. 'The palace means nothing to me without you,' he had declared. The people of Ayodhya lined the streets. They were not cheering. They were sobbing. They watched their beloved prince walk away, and their hearts shattered into a thousand pieces. Ram did not look back. He did not wipe his tears. He walked with his back straight, his chin up, and his steps steady. He walked through the city, through the countryside, through the villages. He did not complain. He did not curse his fate. He walked into the forest—dark, wild, unfamiliar—and he smiled. He turned to Sita and Lakshman and said, 'Look at what we have. We have each other. We have the trees for shelter, the rivers for water, the birds for music. This is not a punishment. This is an adventure.'",
        hi: "महल के द्वार खुले। राम बाहर निकले। उन्होंने वल्कल वस्त्र पहने थे—खुरदरे, खुजली वाले, उस रेशम से बिल्कुल अलग जो क्षणों पहले उन्होंने पहना था। उनके पास कोई रथ नहीं था, कोई नौकर नहीं था, कोई रक्षक नहीं था। बस उनके नंगे पैर और एक लाठी। उनके पीछे सीता चल रही थीं, उनकी पत्नी, जिन्होंने पीछे रहने से इनकार कर दिया था। 'मेरे पति जहाँ जाते हैं, वही मेरा घर है,' उन्होंने शांत दृढ़ता के साथ कहा था। उनके साथ लक्ष्मण चल रहे थे, उनके भाई, जिन्होंने उनकी जान की रक्षा करने की शपथ ली थी। 'तुम्हारे बिना महल मेरे लिए कुछ भी नहीं है,' उन्होंने घोषणा की थी। अयोध्या के लोग सड़कों पर खड़े थे। वे जयकार नहीं कर रहे थे। वे सिसक रहे थे। वे अपने प्रिय राजकुमार को जाते देख रहे थे, और उनके हृदय हजार टुकड़ों में बिखर रहे थे। राम ने पीछे मुड़कर नहीं देखा। उन्होंने अपने आँसू नहीं पोंछे। वह सीधी पीठ, ऊँची ठुड्डी और स्थिर कदमों के साथ चले। वह शहर से, ग्रामीण इलाकों से, गाँवों से गुजरे। उन्होंने शिकायत नहीं की। उन्होंने अपने भाग्य को कोसा नहीं। वह अंधेरे, जंगली, अपरिचित वन में गए—और वह मुस्कुराए। उन्होंने सीता और लक्ष्मण की ओर मुड़कर कहा, 'देखो हमारे पास क्या है। हम एक दूसरे के साथ हैं। हमारे पास आश्रय के लिए वृक्ष हैं, पानी के लिए नदियाँ हैं, संगीत के लिए पक्षी हैं। यह सजा नहीं है। यह एक साहसिक यात्रा है।'",
        sa: "महलद्वारे उद्घाटिते। रामः बहिः निर्गतः। सः वल्कलानि परिधितवान्—रूक्षाणि, कण्डूयमानानि, तस्मात् रेशमात् भिन्नानि यत् क्षणेभ्यः पूर्वम् सः परिधितवान्। तस्य रथः न आसीत्, सेवकाः न आसन्, रक्षकाः न आसन्। केवलम् तस्य अनंगुलिपादौ यष्टिः च। तस्य पृष्ठतः सीता अगच्छत्, तस्य पत्नी, या पश्चात् स्थातुम् न अइच्छत्। 'मम पतिः यत्र गच्छति, तत् मम गृहम्,' सा शान्तदृढतया अवदत्। तस्य पार्श्वे लक्ष्मणः अगच्छत्, तस्य भ्राता, यः प्राणैः रक्षितुम् प्रतिज्ञातवान्। 'त्वां विना महलः मम किमपि नास्ति,' सः अघोषयत्। अयोध्यायाः जनाः मार्गेषु स्थिताः। न जयध्वनिम् अकुर्वन्। अरोदन्। स्वप्रियम् राजकुमारम् गच्छन्तम् पश्यन्ति स्म, तेषाम् हृदयानि सहस्रशः भग्नानि। रामः न परावृत्तः। न अश्रूणि प्रमृष्टवान्। सः स्थिरपृष्ठः, उन्नतचिबुकः, दृढपदैः अगच्छत्। सः नगरम्, ग्रामीणक्षेत्रम्, ग्रामान् च अगच्छत्। न अशिक्षत। न दैवम् अशपत्। सः वनम्—अन्धकारम्, वन्यम्, अपरिचितम्—अगच्छत्, सः स्मितम् अकरोत्। सः सीताम् लक्ष्मणम् च उक्त्वा अवदत्, 'पश्य किम् अस्माकम् अस्ति। अस्माकम् अन्योन्यम् अस्ति। आश्रयाय वृक्षाः, जलाय नद्यः, गीताय पक्षिणः। एतत् दण्डः नास्ति। एतत् साहसिकयात्रा अस्ति।'",
        question: "What is the 'forest' that life is asking you to enter? What have you lost that you need to see as not a loss, but a new beginning?",
        answer: "Ram could have spent the rest of his life angry at Kaikeyi. He could have cursed the gods for his fate. He could have sat in that forest and cried for fourteen years. He did not. He chose to see the forest as an adventure, not a punishment. He chose to focus on what he had, not what he had lost. He chose to walk forward with grace, not backward with bitterness.",
        takeaway: "Your comfort zone is not your destiny. When life forces you into the forest, do not mourn the palace. Embrace the trees. Embrace the unknown. Turn your exile into adventure. The greatest transformations begin when you step outside what is comfortable."
    },

    // ============================================================
    // CHAPTER 5: Ayodhya Kanda - The Power of Loyalty
    // ============================================================
    {
        id: 5,
        title: "Ayodhya Kanda - The Power of Loyalty",
        image: "ramayan-images/lakshman-sita.jpg",
        setting: "When the world turns its back on you, who stands beside you? And more importantly—whose world will you never turn your back on?",
        en: "When Ram announced his exile, the world fell silent. But two voices rose above the silence. Sita stepped forward first. 'I am coming with you,' she said. Ram tried to convince her otherwise. 'The forest is dangerous. There are wild animals. There are demons. You are a princess. You were raised in luxury. You will suffer.' Sita looked at him with fire in her eyes. 'I am not a princess when I am with you. I am your wife. And a wife's place is with her husband. Wherever you go, that is my home. Whatever you eat, that is my food. Whatever you wear, that is my clothing. You cannot leave me behind. I will follow you into the flames, and I will follow you into paradise. There is no in-between.' Ram could not argue. He could only love her. Then Lakshman stepped forward. He did not speak many words. He simply picked up his weapons, stood beside Ram, and said, 'I go where you go, brother. The palace is empty without you. The throne means nothing to me. I will sleep on the forest floor beside you, and I will gladly eat roots and berries. My life is not mine; it is yours.' In the forest, Lakshman stayed awake every night, guarding Ram and Sita with his life. He never complained. He never asked for thanks. He served in silence, because that is what loyalty demands.",
        hi: "जब राम ने अपने वनवास की घोषणा की, तो दुनिया सन्नाटे में डूब गई। लेकिन दो आवाज़ें इस सन्नाटे से ऊपर उठीं। सीता पहले आगे बढ़ीं। 'मैं तुम्हारे साथ आ रही हूँ,' उन्होंने कहा। राम ने उन्हें मनाने की कोशिश की। 'वन खतरनाक है। वहाँ जंगली जानवर हैं। राक्षस हैं। तुम एक राजकुमारी हो। तुम विलासिता में पली-बढ़ी हो। तुम कष्ट उठाओगी।' सीता ने उन्हें आग की आँखों से देखा। 'मैं तुम्हारे साथ होने पर राजकुमारी नहीं हूँ। मैं तुम्हारी पत्नी हूँ। और एक पत्नी का स्थान उसके पति के साथ होता है। तुम जहाँ जाओगे, वही मेरा घर होगा। तुम जो खाओगे, वही मेरा भोजन होगा। तुम जो पहनोगे, वही मेरा वस्त्र होगा। तुम मुझे पीछे नहीं छोड़ सकते। मैं तुम्हारे पीछे आग में चलूँगी, और मैं तुम्हारे पीछे स्वर्ग में चलूँगी। कोई बीच का रास्ता नहीं है।' राम बहस नहीं कर सके। वे केवल उससे प्रेम कर सकते थे। फिर लक्ष्मण आगे बढ़े। उन्होंने कई शब्द नहीं बोले। उन्होंने बस अपने हथियार उठाए, राम के साथ खड़े हुए, और कहा, 'मैं वहाँ जाता हूँ जहाँ तुम जाते हो, भाई। तुम्हारे बिना महल खाली है। सिंहासन मेरे लिए कुछ नहीं है। मैं तुम्हारे साथ जंगल की जमीन पर सोऊँगा, और मैं खुशी से जड़ें और जामुन खाऊँगा। मेरा जीवन मेरा नहीं है; यह तुम्हारा है।' वन में, लक्ष्मण हर रात जागते रहे, राम और सीता की अपनी जान देकर रक्षा करते रहे। उन्होंने कभी शिकायत नहीं की। कभी धन्यवाद नहीं माँगा। उन्होंने चुपचाप सेवा की, क्योंकि वफादारी यही माँग करती है।",
        sa: "यदा रामः वनवासम् अघोषयत्, लोकः मौनेन अशून्यः अभवत्। किन्तु द्वे स्वरे एतस्मात् मौनात् उन्नते। सीता प्रथमा अग्रसरा अभवत्। 'अहं त्वया सह आगच्छामि,' सा अवदत्। रामः ताम् अन्यथा स्थापयितुम् अयतत। 'वनम् भयानकम् अस्ति। तत्र वन्यपशवः सन्ति। राक्षसाः सन्ति। त्वं राजकुमारी। त्वं विलासितायाम् वर्धिता। त्वं कष्टम् भोक्ष्यसे।' सीता अग्निनेत्रैः तम् अद्राक्षीत्। 'अहं त्वया सह राजकुमारी नास्मि। अहं तव पत्नी। पत्न्याः स्थानम् पत्या सह भवति। त्वं यत्र गच्छसि, तत् मम गृहम्। त्वं यत् खादसि, तत् मम भोजनम्। त्वं यत् परिधत्से, तत् मम वस्त्रम्। त्वं माम् पश्चात् त्यक्तुम् न शक्नोषि। अहं त्वया सह अग्निम् गमिष्यामि, स्वर्गम् गमिष्यामि। मध्यमार्गः नास्ति।' रामः न विवादितुम् अशक्नोत्। केवलम् ताम् प्रेमितुम् शक्नोत्। तदा लक्ष्मणः अग्रसरः अभवत्। सः बहूनि वचनानि न अवदत्। केवलम् अस्त्राणि उत्थाय, रामस्य पार्श्वे स्थित्वा, अवदत्, 'अहं यत्र त्वं गच्छसि, तत्र गच्छामि, भ्रातः। त्वां विना महलः रिक्तः। सिंहासनम् मम किमपि नास्ति। अहं त्वया सह वनभूमौ शयिष्यामि, मूलानि फलानि च आहरिष्यामि। मम जीवनम् मम नास्ति; तव अस्ति।' वने, लक्ष्मणः प्रतिरात्रम् जागरूकः आसीत्, रामम् सीताम् च प्राणैः रक्षन्। न कदापि अशिक्षत। न कृतज्ञताम् अयाचत। मौनेन सेवाम् अकरोत्, यतः निष्ठा एतत् मागयति।",
        question: "Who are the people who would walk into the forest for you? And more importantly, whose forest are you willing to walk into?",
        answer: "Ram never demanded loyalty. He never said, 'You must follow me.' He simply lived his life with such integrity, such love, such grace, that Sita and Lakshman could not imagine staying behind. Loyalty is not something you demand; it is something you earn. It is built through trust, through kindness, through showing up for others day after day.",
        takeaway: "Be the kind of person that others would follow into the forest. And when you find those people who stay by your side, honor them. Protect them. Love them. Loyalty is the rarest gift in the world—treasure it."
    },

    // ============================================================
    // CHAPTER 6: Aranya Kanda - The Illusion of Desire
    // ============================================================
    {
        id: 6,
        title: "Aranya Kanda - The Illusion of Desire",
        image: "ramayan-images/golden-deer.jpg",
        setting: "Have you ever chased something so beautiful, so perfect, that you forgot everything else? And when you finally caught it, you realized it was all an illusion?",
        en: "The forest was alive with sounds. Birds sang. Wind whispered through the leaves. And then, Sita saw it. A golden deer. It was unlike anything she had ever seen. Its fur shimmered like sunlight on liquid gold. Its hooves sparkled with every step. It moved with a grace that seemed almost divine. 'Ram, look!' Sita gasped. 'I have never seen anything so beautiful. Please, catch it for me.' Ram looked at the deer. Something was wrong. A golden deer does not exist in nature. It was too perfect, too beautiful, too impossible. But Sita's eyes were full of wonder. Ram loved her. He could not say no. 'Stay here with Lakshman,' he told her. 'I will bring it back.' And he ran into the forest. He ran faster and faster, chasing the deer deeper and deeper into the wilderness. The deer led him away from Sita, away from safety, away from everything that mattered. When Ram finally shot his arrow, the deer screamed—but it was not the scream of a deer. It was the scream of a demon. 'Lakshman! Help me!' it shrieked in Ram's own voice. Back at the hut, Sita heard the scream. Panic flooded her heart. 'Lakshman, go help your brother!' Lakshman refused. 'He told me to protect you.' But Sita's words cut through him. 'Do you not love your brother? He is dying! GO!' Lakshman left. And in that moment, the trap was complete. Ravana arrived, disguised as a sage, and kidnapped Sita. The golden deer was never real. It was just an illusion, a trap, a lie.",
        hi: "वन जीवंत था। पक्षी गा रहे थे। हवा पत्तियों के बीच फुसफुसा रही थी। और फिर, सीता ने उसे देखा। एक सुनहला हिरण। यह उन सब से अलग था जो उसने कभी देखा था। इसकी खाल सूर्य की किरणों पर तरल सोने की तरह चमकती थी। इसके खुर हर कदम पर चमकते थे। यह ऐसी सुंदरता से चलता था जो लगभग दिव्य लगती थी। 'राम, देखो!' सीता ने हाँफते हुए कहा। 'मैंने इतनी सुंदर चीज कभी नहीं देखी। कृपया, इसे मेरे लिए पकड़ो।' राम ने हिरण को देखा। कुछ गड़बड़ थी। प्रकृति में सुनहला हिरण नहीं होता। यह बहुत सही था, बहुत सुंदर, बहुत असंभव। लेकिन सीता की आँखें आश्चर्य से भरी थीं। राम उससे प्यार करते थे। वह मना नहीं कर सकते थे। 'लक्ष्मण के साथ यहीं रहो,' उन्होंने उससे कहा। 'मैं इसे वापस लाऊँगा।' और वह जंगल में भाग गए। वह तेज़ और तेज़ भागते गए, हिरण का पीछा करते हुए जंगल में गहरे और गहरे चले गए। हिरण उन्हें सीता से, सुरक्षा से, और हर उस चीज से दूर ले गया जो मायने रखती थी। जब राम ने आखिरकार अपना तीर चलाया, तो हिरण चिल्लाया—लेकिन यह हिरण की चीख नहीं थी। यह एक राक्षस की चीख थी। 'लक्ष्मण! मेरी मदद करो!' यह राम की ही आवाज़ में चीखा। झोपड़ी में वापस, सीता ने चीख सुनी। घबराहट ने उसके हृदय को भर दिया। 'लक्ष्मण, अपने भाई की मदद करो!' लक्ष्मण ने मना कर दिया। 'उन्होंने मुझे तुम्हारी रक्षा करने को कहा है।' लेकिन सीता के शब्दों ने उन्हें छेद दिया। 'क्या तुम अपने भाई से प्यार नहीं करते? वह मर रहा है! जाओ!' लक्ष्मण चले गए। और उसी क्षण, जाल पूरा हो गया। रावण, एक ऋषि के वेश में, आया और सीता का अपहरण कर लिया। सुनहला हिरण कभी वास्तविक नहीं था। यह सिर्फ एक भ्रम था, एक जाल, एक झूठ।",
        sa: "वनम् जीवन्तम् आसीत्। पक्षिणः अगायन्। वायुः पर्णेषु अशुश्रावयत्। तदा, सीता तम् अपश्यत्। सुवर्णमृगम्। तत् तस्याः दृष्टम् सर्वस्मात् भिन्नम् आसीत्। तस्य चर्म सूर्यकिरणेषु द्रवसुवर्णवत् अचकचत्। तस्य खुराः प्रतिपदम् अचकचन्। सः दिव्यमिव लावण्येन अचलत्। 'राम, पश्य!' सीता अश्वसत्। 'अहम् एतादृशम् सुन्दरम् न कदापि दृष्टवती। कृपया, मम कृते आनय।' रामः मृगम् ददर्श। किमपि अनिष्टम् आसीत्। सुवर्णमृगः प्रकृतौ न विद्यते। अतिसुन्दरः, अत्यद्भुतः, अत्यसम्भवः आसीत्। किन्तु सीतायाः नेत्रे विस्मयेन परिपूर्णे। रामः ताम् अप्रियत्। सः न अशक्नोत् नकारितुम्। 'अत्र लक्ष्मणेन सह तिष्ठ,' सः ताम् अवदत्। 'अहम् आनेष्यामि।' सः वनम् अधावत्। सः अधिकम् अधिकम् अवर्तत, मृगम् अन्वधावन् वने गहनम् गहनम्। मृगः तम् सीतायाः, रक्षायाः, सर्वस्मात् महत्त्वपूर्णात् दूरम् अनयत्। यदा रामः अन्ते बाणम् अमुञ्चत्, मृगः अचीत्करोत्—किन्तु तत् मृगस्य चीत्कारः न आसीत्। तत् राक्षसस्य चीत्कारः आसीत्। 'लक्ष्मण! माम् रक्ष!' इति रामस्य स्वरेण अचीत्करोत्। कुटीरे, सीता चीत्कारम् अशृणोत्। भयम् तस्याः हृदयम् अपूरयत्। 'लक्ष्मण, भ्रातुः साहाय्यम् कुरु!' लक्ष्मणः न अंगीकरोत्। 'सः माम् रक्षितुम् अकथयत्।' किन्तु सीतायाः वचनानि तम् अताडयन्। 'किं त्वं भ्रातरम् न प्रियसि? सः म्रियते! गच्छ!' लक्ष्मणः अगच्छत्। तस्मिन् क्षणे, जालम् पूर्णम् अभवत्। रावणः, ऋषिवेषेण, आगत्य सीताम् अपहृतवान्। सुवर्णमृगः कदापि वास्तविकः न आसीत्। सः केवलम् माया आसीत्, जालम्, असत्यम्।",
        question: "What is the 'golden deer' in your life? What desire looks so beautiful that you are willing to abandon everything to chase it?",
        answer: "Ram knew the deer was a trap. He felt it in his gut. But he ignored his instinct because he loved Sita and wanted to make her happy. That is the danger of desire—it makes you ignore your instincts. It makes you chase illusions. The golden deer was never real. It was just a reflection of Sita's desires, magnified by a demon's magic. And it cost her everything.",
        takeaway: "Pause before you chase something that looks too good to be true. Not everything that glitters is gold. Your instincts are there to protect you. Trust them. The most beautiful things in life are rarely the most glittering."
    },

    // ============================================================
    // CHAPTER 7: Aranya Kanda - The Heartbreak of Loss
    // ============================================================
    {
        id: 7,
        title: "Aranya Kanda - The Heartbreak of Loss",
        image: "ramayan-images/ram-grief.jpg",
        setting: "Have you ever lost something so precious that you felt your heart shatter into pieces? How do you go on when the thing you loved most in the world is taken from you?",
        en: "Ram returned to the hut. It was empty. He called her name once, twice, a hundred times. The forest echoed back with silence. He fell to his knees. The greatest warrior in the world was on the ground, weeping. His wife was gone. The love of his life had been stolen. He had failed her. He had failed to protect her. The pain was unbearable. It was a knife twisting in his chest. But then, something shifted inside him. He wiped his tears. He stood up. He looked at the forest with new eyes. 'I will find her,' he said, his voice cracking with grief but burning with determination. 'I will not stop until I find her. I will cross oceans. I will fight armies. I will defeat demons. Nothing will stop me. Nothing.' He did not stay on the ground. He did not give up. He asked the trees if they had seen her. He asked the rivers, the birds, the animals. He turned his grief into purpose. He turned his pain into fuel. Every step he took from that moment was a step of love—love for Sita, love for the truth, love for the life they had built together.",
        hi: "राम झोपड़ी में वापस लौटे। यह खाली थी। उन्होंने उसका नाम एक बार, दो बार, सौ बार पुकारा। वन ने मौन के साथ प्रतिध्वनि दी। वह अपने घुटनों पर गिर पड़े। दुनिया का सबसे महान योद्धा जमीन पर लोट रहा था, रो रहा था। उसकी पत्नी चली गई थी। उसके जीवन का प्यार चुरा लिया गया था। वह उसे विफल कर चुका था। वह उसकी रक्षा करने में विफल हो गया था। दर्द असहनीय था। यह उसकी छाती में घूमता एक चाकू था। लेकिन फिर, उसके अंदर कुछ बदल गया। उसने अपने आँसू पोंछे। वह खड़ा हो गया। उसने वन को नई आँखों से देखा। 'मैं उसे ढूँढूँगा,' उसने कहा, उसकी आवाज़ दुःख से टूट रही थी लेकिन दृढ़ संकल्प से जल रही थी। 'मैं तब तक नहीं रुकूँगा जब तक मैं उसे नहीं पा लेता। मैं समुद्र पार करूँगा। मैं सेनाओं से लड़ूँगा। मैं राक्षसों को हराऊँगा। मुझे कुछ भी नहीं रोक सकता। कुछ भी नहीं।' वह जमीन पर नहीं रुका। उसने हार नहीं मानी। उसने पेड़ों से पूछा कि क्या उन्होंने उसे देखा है। उसने नदियों से, पक्षियों से, जानवरों से पूछा। उसने अपने दुःख को उद्देश्य में बदल दिया। उसने अपने दर्द को ईंधन में बदल दिया। उस क्षण से उसने जो भी कदम उठाया, वह प्रेम का कदम था—सीता के लिए प्रेम, सत्य के लिए प्रेम, उस जीवन के लिए प्रेम जो उन्होंने एक साथ बनाया था।",
        sa: "रामः कुटीरम् आगत्य रिक्तम् अपश्यत्। सः तस्याः नाम एकवारम्, द्विवारम्, शतवारम् अकथयत्। वनम् मौनेन प्रतिध्वनिम् अयच्छत्। सः जानुभ्याम् अपतत्। लोकस्य महान् योद्धा भूमौ रुदन् आसीत्। तस्य पत्नी गता आसीत्। तस्य जीवनप्रेम चोरितम्। सः ताम् विफलितवान्। सः ताम् रक्षितुम् विफलितवान्। पीडा असह्या आसीत्। सा तस्य वक्षसि वलिता कृपाणी आसीत्। किन्तु तदा, तस्य अन्तः किमपि परिवर्तितम्। सः अश्रूणि प्रमृष्टवान्। सः उत्थितवान्। सः वनम् नवाभ्याम् नेत्राभ्याम् ददर्श। 'अहं ताम् अन्वेषयिष्यामि,' सः अवदत्, तस्य वाणी दुःखेन भिन्ना किन्तु दृढसंकल्पेन दीप्ता। 'अहं यावत् न प्राप्नुयाम्, न स्थास्यामि। अहं समुद्रान् लङ्घयिष्यामि। अहं सेनाः योधयिष्यामि। अहं राक्षसान् पराजयिष्यामि। माम् किमपि न स्तम्भयिष्यति। किमपि न।' सः भूमौ न अतिष्ठत्। न हारम् अमन्यत। सः वृक्षान् अपृच्छत् किं ते ताम् ददृशुः। नदीः, पक्षिणः, पशून् च अपृच्छत्। सः दुःखम् उद्देश्ये परिणतवान्। सः पीडाम् इन्धने परिणतवान्। तस्मात् क्षणात् तेन कृतम् प्रतिपदम् प्रेम्णः पदम् आसीत्—सीतायै प्रेम, सत्याय प्रेम, तस्मै जीवनाय प्रेम यत् तौ सह निर्मितवन्तौ।",
        question: "What loss are you carrying right now that you need to turn into purpose? What pain is waiting to become fuel for your next step?",
        answer: "Ram did not pretend the loss did not hurt. He let himself feel the full weight of it. He collapsed. He wept. He grieved. But he did not stay there. He understood that Sita needed him—she was waiting for him. And she needed him to act, not to cry. He honored his love by doing everything in his power to find her. He turned his pain into purpose.",
        takeaway: "Loss is not the end. It is a turning point. Let yourself grieve—fully, deeply, completely. But do not stay there. Get up. Wipe your tears. Take a step. The people who love you need you to keep moving. Turn your pain into purpose."
    },

    // ============================================================
    // CHAPTER 8: Kishkindha Kanda - Finding Your Hanuman
    // ============================================================
    {
        id: 8,
        title: "Kishkindha Kanda - Finding Your Hanuman",
        image: "ramayan-images/hanuman-faith.jpg",
        setting: "Do you believe you can do it all alone? Or have you realized that even the strongest warriors need allies, friends, and believers?",
        en: "Ram walked through the forest, searching for Sita. But the forest was vast. He could search for a thousand years and never find her. He needed help. He needed allies. He needed a miracle. And then, he met Hanuman. Hanuman was a vanara—a creature with the face of a monkey and the heart of a devotee. He was intelligent beyond measure, strong beyond imagination, and devoted beyond reason. But he did not know his own strength. He had forgotten who he was. He had forgotten the power that lay dormant inside him. Ram looked at Hanuman and saw something Hanuman could not see in himself. He saw potential. He saw greatness. He saw a being who could cross oceans, defeat demons, and change the course of history. Ram did not just use Hanuman. He believed in him. He said, 'You have the power to find Sita. You have the power to leap across the ocean. You have the power to bring hope back to the world. Do you believe it?' Hanuman looked at Ram and felt something stir in his chest. He had never believed in himself. But he believed in Ram. And that was enough. He said, 'I will go. I will find her. I will not fail you.' And he leaped into the sky, flying across the ocean, carrying Ram's hope with him.",
        hi: "राम वन में सीता की खोज में चल रहे थे। लेकिन वन विशाल था। वे हजार वर्षों तक खोज सकते थे और कभी उसे नहीं पा सकते थे। उन्हें मदद की आवश्यकता थी। उन्हें सहयोगियों की आवश्यकता थी। उन्हें एक चमत्कार की आवश्यकता थी। और फिर, उनकी मुलाकात हनुमान से हुई। हनुमान एक वानर थे—बंदर का चेहरा और भक्त का हृदय रखने वाला प्राणी। वह माप से परे बुद्धिमान, कल्पना से परे शक्तिशाली, और कारण से परे समर्पित थे। लेकिन वह अपनी शक्ति को नहीं जानते थे। वह भूल गए थे कि वह कौन थे। वह भूल गए थे कि उनके अंदर कौन सी शक्ति निष्क्रिय पड़ी थी। राम ने हनुमान को देखा और उनमें वह देखा जो हनुमान स्वयं में नहीं देख सकते थे। उन्होंने क्षमता देखी। उन्होंने महानता देखी। उन्होंने एक ऐसे प्राणी को देखा जो समुद्र पार कर सकता था, राक्षसों को हरा सकता था, और इतिहास की धारा बदल सकता था। राम ने केवल हनुमान का उपयोग नहीं किया। उन्होंने उन पर विश्वास किया। उन्होंने कहा, 'तुममें सीता को खोजने की शक्ति है। तुममें समुद्र पार करने की शक्ति है। तुममें दुनिया में आशा वापस लाने की शक्ति है। क्या तुम विश्वास करते हो?' हनुमान ने राम को देखा और कुछ उनके सीने में हिल गया। उन्होंने कभी खुद पर विश्वास नहीं किया था। लेकिन उन्होंने राम पर विश्वास किया। और यह काफी था। उन्होंने कहा, 'मैं जाऊँगा। मैं उसे ढूँढूँगा। मैं तुम्हें विफल नहीं करूँगा।' और वह आकाश में कूद गए, समुद्र के पार उड़ते हुए, राम की आशा को अपने साथ लेकर।",
        sa: "रामः वने सीताम् अन्वेषयन् अगच्छत्। किन्तु वनम् विशालम् आसीत्। सः सहस्रम् वर्षाणि अन्वेषयेत् अपि न प्राप्नुयात्। तस्य साहाय्यम् आवश्यकम्। सहयोगिनः आवश्यकाः। चमत्कारः आवश्यकः। तदा, सः हनुमन्तम् मिलितवान्। हनुमान् वानरः आसीत्—वानरमुखः भक्तहृदयः प्राणी। सः मानातीतम् बुद्धिमान्, कल्पनातीतम् बलवान्, कारणातीतम् समर्पितः च आसीत्। किन्तु सः स्वबलम् न जानाति स्म। सः विस्मृतवान् यः सः। सः विस्मृतवान् यत् तस्य अन्तः निष्क्रियम् बलम्। रामः हनुमन्तम् दृष्ट्वा तम् अपश्यत् यत् हनुमान् स्वयम् न अपश्यत्। सः सामर्थ्यम् अपश्यत्। सः महत्त्वम् अपश्यत्। सः तम् प्राणिम् अपश्यत् यः समुद्रम् लङ्घयेत्, राक्षसान् पराजयेत्, इतिहासस्य गतिम् परिवर्तयेत्। रामः केवलम् हनुमन्तम् न अयुङ्क्त। सः तस्मिन् विश्वस्तवान्। सः अवदत्, 'त्वयि सीताम् अन्वेषितुम् बलम् अस्ति। त्वयि समुद्रम् लङ्घयितुम् बलम् अस्ति। त्वयि जगति आशाम् पुनः आनेतुम् बलम् अस्ति। किं त्वं विश्वसिषि?' हनुमान् रामम् दृष्ट्वा किमपि तस्य वक्षसि अचलत्। सः कदापि स्वयम् न अविश्वसीत्। किन्तु सः रामे अविश्वसीत्। तत् पर्याप्तम् आसीत्। सः अवदत्, 'अहं गमिष्यामि। अहं ताम् अन्वेषयिष्यामि। अहं त्वां न विफलयिष्यामि।' सः गगनम् अप्लवत, समुद्रम् उपरि पतन्, रामस्य आशाम् स्वेन सह वहन्।",
        question: "Who is the 'Hanuman' that you need to find in your life? And more importantly, whose Hanuman are you meant to be?",
        answer: "Ram was the strongest warrior in the world. He had defeated demons that no one else could defeat. But he still asked for help. He still trusted someone else with his greatest mission. He saw the potential in Hanuman that Hanuman could not see in himself. Sometimes, we need someone else to believe in us before we can believe in ourselves.",
        takeaway: "Do not try to carry your burdens alone. Find your Hanuman. And if you are someone's Hanuman, remind them of their strength. Sometimes, a single word of belief can unlock the power that has been sleeping inside someone for years."
    },

    // ============================================================
    // CHAPTER 9: Sundara Kanda - The Power of Faith
    // ============================================================
    {
        id: 9,
        title: "Sundara Kanda - The Power of Faith",
        image: "ramayan-images/hanuman-leap.jpg",
        setting: "What happens when you stand at the edge of your own ocean? When what you need to cross seems impossible and you cannot see the other side—do you leap or do you turn back?",
        en: "Hanuman stood at the edge of the ocean. The water stretched to the horizon, endless and terrifying. He could not see the other side. He could not see Lanka. He could not see Sita. All he could see was the vast, dark, churning water. He had no boat. No bridge. No map. No help. Just himself, and his faith. He closed his eyes. He remembered Ram's words. He remembered the fire in Ram's eyes when he said, 'You can do this.' He remembered Sita, waiting for someone to save her. He remembered the purpose that had been given to him. He opened his eyes. He looked at the ocean. He said, 'You are just water. I am the servant of Ram. I will cross you.' And he leaped. The wind howled. The waves rose to swallow him. The demons in the ocean tried to drag him down. But Hanuman did not stop. He did not look back. He did not doubt. He flew across that ocean with nothing but faith. And when he reached Lanka, when he finally found Sita, he fell at her feet and said, 'I have come. Ram has sent me. You are not alone.'",
        hi: "हनुमान समुद्र के किनारे खड़े थे। पानी क्षितिज तक फैला था, अनंत और भयानक। उन्हें दूसरा किनारा नहीं दिख रहा था। उन्हें लंका नहीं दिख रही थी। उन्हें सीता नहीं दिख रही थीं। बस विशाल, अंधकारमय, उबलता हुआ पानी दिख रहा था। उनके पास कोई नाव नहीं थी। कोई पुल नहीं था। कोई नक्शा नहीं था। कोई मदद नहीं थी। बस वे थे, और उनका विश्वास था। उन्होंने अपनी आँखें बंद कर लीं। उन्होंने राम के शब्दों को याद किया। उन्होंने राम की आँखों में आग को याद किया जब उन्होंने कहा था, 'तुम यह कर सकते हो।' उन्होंने सीता को याद किया, जो उन्हें बचाने के लिए किसी की प्रतीक्षा कर रही थीं। उन्होंने उस उद्देश्य को याद किया जो उन्हें दिया गया था। उन्होंने अपनी आँखें खोलीं। उन्होंने समुद्र को देखा। उन्होंने कहा, 'तुम सिर्फ पानी हो। मैं राम का सेवक हूँ। मैं तुम्हें पार करूँगा।' और वे कूद पड़े। हवा चीख उठी। लहरें उन्हें निगलने के लिए उठीं। समुद्र में राक्षसों ने उन्हें नीचे खींचने की कोशिश की। लेकिन हनुमान नहीं रुके। उन्होंने पीछे मुड़कर नहीं देखा। उन्होंने संदेह नहीं किया। वे केवल विश्वास के साथ उस समुद्र के पार उड़े। और जब वे लंका पहुँचे, जब उन्होंने आखिरकार सीता को पाया, तो वे उनके चरणों में गिर गए और कहा, 'मैं आया हूँ। राम ने मुझे भेजा है। तुम अकेली नहीं हो।'",
        sa: "हनुमान् समुद्रतीरे अतिष्ठत्। जलम् क्षितिजम् यावत् विस्तृतम्, अनन्तम्, भयानकम्। सः परम् तीरम् न अपश्यत्। सः लङ्काम् न अपश्यत्। सः सीताम् न अपश्यत्। केवलम् विशालम्, अन्धकारम्, क्षुभितम् जलम् अपश्यत्। तस्य नौका न आसीत्। न सेतुः। न मानचित्रम्। न साहाय्यम्। केवलम् सः, तस्य विश्वासः च। सः नेत्रे पिदधौ। सः रामस्य वचनानि स्मृतवान्। सः रामस्य नेत्रयोः अग्निम् स्मृतवान् यदा सः अवदत्, 'त्वम् एतत् कर्तुम् शक्नोषि।' सः सीताम् स्मृतवान्, या तम् रक्षितुम् कस्यचित् प्रतीक्षा करोति। सः तम् उद्देश्यम् स्मृतवान् यः तस्मै प्रदत्तः आसीत्। सः नेत्रे उद्घाटितवान्। सः समुद्रम् ददर्श। सः अवदत्, 'त्वम् केवलम् जलम् असि। अहं रामस्य सेवकः। अहं त्वाम् लङ्घयिष्यामि।' सः अप्लवत। वायुः अक्रोशत्। तरङ्गाः तम् ग्रसितुम् उत्थिताः। समुद्रे राक्षसाः तम् अधः आकर्षितुम् अयतन्त। किन्तु हनुमान् न अरमत। न परावृत्तः। न सन्दिग्धः। सः केवलम् विश्वासेन समुद्रम् उपरि अपतत्। यदा सः लङ्काम् प्राप्नुवत्, यदा सः अन्ते सीताम् अपश्यत्, सः तस्याः पादयोः अपतत् अवदत् च, 'अहम् आगतः। रामः माम् प्रेषितवान्। त्वं एकाकिनी नासि।'",
        question: "What is the 'ocean' that you are standing at the edge of right now? What leap of faith are you afraid to take?",
        answer: "Hanuman did not know if he would survive. He did not know if Sita was even alive. He had no guarantees, no backup, no plan B. He had only faith—faith in Ram, faith in his purpose, and faith in himself. And that faith carried him across the ocean. Faith is not the absence of fear; it is the decision to act despite fear.",
        takeaway: "The ocean is vast, but you are bigger than you know. The person you are meant to be is waiting on the other side. Leap. You will find your way. Faith is not knowing the outcome; it is trusting the journey."
    },

    // ============================================================
    // CHAPTER 10: Yuddha Kanda - The Righteous Anger
    // ============================================================
    {
        id: 10,
        title: "Yuddha Kanda - The Righteous Anger",
        image: "ramayan-images/warrior-ram.jpg",
        setting: "Is all anger bad? Or is there a kind of anger that is actually necessary? A fire that burns inside you when you see something wrong, and demands that you act?",
        en: "The war had begun. Ram had built a bridge across the ocean. He had marched his army into Lanka. He had done everything he could to avoid this—he had given Ravana chance after chance to return Sita peacefully. But Ravana had mocked him. Ravana had laughed at his mercy. Ravana had said, 'You are just a human. I am the king of demons. You cannot defeat me.' Something snapped inside Ram. His eyes changed. His posture changed. His voice dropped to a whisper that carried more power than any shout. He said, 'You have taken my wife. You have destroyed my peace. You have insulted my love. You have had your chances. Now you will have justice.' And he entered the battlefield. But this was not blind rage. This was righteous anger. He was not fighting out of hatred; he was fighting out of love. He was not fighting to kill; he was fighting to protect. He aimed every arrow with precision. He fought with intelligence, not just strength. He was a warrior, but he was also a husband, a brother, a king. And he would not let injustice win.",
        hi: "युद्ध शुरू हो चुका था। राम ने समुद्र के पार एक पुल बनाया था। उन्होंने अपनी सेना को लंका में ले जाया था। उन्होंने इससे बचने के लिए हर संभव प्रयास किया था—उन्होंने रावण को सीता को शांतिपूर्वक वापस करने का बार-बार मौका दिया था। लेकिन रावण ने उनका मजाक उड़ाया था। रावण ने उनकी दया पर हँसा था। रावण ने कहा था, 'तुम सिर्फ एक मानव हो। मैं राक्षसों का राजा हूँ। तुम मुझे हरा नहीं सकते।' राम के अंदर कुछ टूट गया। उनकी आँखें बदल गईं। उनकी मुद्रा बदल गई। उनकी आवाज़ एक फुसफुसाहट में बदल गई जिसमें किसी भी चीख से अधिक शक्ति थी। उन्होंने कहा, 'तुमने मेरी पत्नी को ले लिया। तुमने मेरी शांति नष्ट कर दी। तुमने मेरे प्रेम का अपमान किया। तुम्हें अपने मौके मिल चुके हैं। अब तुम्हें न्याय मिलेगा।' और वह युद्धभूमि में प्रवेश कर गए। लेकिन यह अंधा क्रोध नहीं था। यह धर्म का क्रोध था। वह घृणा से नहीं लड़ रहे थे; वह प्रेम से लड़ रहे थे। वह मारने के लिए नहीं लड़ रहे थे; वह रक्षा करने के लिए लड़ रहे थे। उन्होंने हर बाण को सटीकता से निशाना बनाया। वह केवल शक्ति से नहीं, बल्कि बुद्धि से लड़े। वह एक योद्धा थे, लेकिन वह एक पति, एक भाई, एक राजा भी थे। और वह अन्याय को जीतने नहीं देते।",
        sa: "युद्धम् आरब्धम् आसीत्। रामः समुद्रे सेतुम् निर्मितवान्। सः सेनाम् लङ्काम् अनीतवान्। सः एतस्य परिहाराय सर्वम् प्रयत्नम् अकरोत्—सः रावणाय सीताम् शान्त्या प्रत्यर्पयितुम् अवसरम् अवसरम् अददात्। किन्तु रावणः तम् उपहसितवान्। रावणः तस्य दयाम् अहसत्। रावणः अवदत्, 'त्वम् केवलम् मानवः। अहं राक्षसानाम् राजा। त्वम् माम् पराजेतुम् न शक्नोषि।' रामस्य अन्तः किमपि भग्नम्। तस्य नेत्रे परिवर्तिते। तस्य मुद्रा परिवर्तिता। तस्य वाणी कर्णध्वनिः अभवत् यस्याम् कस्मात् चीत्कारात् अधिकम् बलम् आसीत्। सः अवदत्, 'त्वम् मम पत्नीम् अहार्षीः। त्वम् मम शान्तिम् नाशितवान्। त्वम् मम प्रेम अपमानितवान्। तव अवसराः प्राप्ताः। अद्य त्वाम् न्यायः प्राप्स्यति।' सः युद्धभूमिम् अगच्छत्। किन्तु एतत् अन्धः क्रोधः न आसीत्। एतत् धर्मक्रोधः आसीत्। सः द्वेषात् न अयुध्यत; सः प्रेम्णा अयुध्यत। सः हन्तुम् न अयुध्यत; सः रक्षितुम् अयुध्यत। सः प्रत्येकम् बाणम् सूक्ष्मत्वेन अमुञ्चत्। सः केवलम् बलेन न, अपितु बुद्ध्या अयुध्यत। सः योद्धा आसीत्, किन्तु सः पतिः, भ्राता, राजा च आसीत्। सः अधर्मम् जयन्तम् न असहते।",
        question: "What is the 'Ravana' in your life? What injustice is happening that deserves your righteous anger and action?",
        answer: "Ram was patient. He gave Ravana chance after chance. He avoided war for as long as possible. But when Ravana refused to do the right thing, Ram did not hold back his anger. He channeled it into action. He did not scream and rage; he fought with precision and purpose. His anger was not destructive; it was transformational. He used his anger to fix what was broken, not to break what was already broken.",
        takeaway: "Anger is not the enemy. Uncontrolled anger is. There is a sacred fire inside you that burns when you see injustice. Use that fire. Stand up for what is right. But do it with control, focus, and purpose. Let your anger be the fuel for change, not the weapon of destruction."
    },

    // ============================================================
    // CHAPTER 11: Yuddha Kanda - The Ultimate Forgiveness
    // ============================================================
    {
        id: 11,
        title: "Yuddha Kanda - The Ultimate Forgiveness",
        image: "ramayan-images/forgiveness.jpg",
        setting: "Is there someone in your life who has hurt you so deeply that you cannot imagine ever forgiving them? What if holding onto that grudge is hurting you more than it is hurting them?",
        en: "The war was over. Ravana lay defeated on the battlefield. Ram had won. He had his wife back. He had his honor back. He had everything he had fought for. And then, he did something no one expected. He asked Hanuman to bring Ravana's body. He ordered that Ravana be given a proper funeral. He said, 'He was a great scholar. He was a great king. He made terrible choices, but he was not a terrible person. He was my enemy, but he was also a Brahmin, a scholar, and a devotee of Shiva. He deserves respect in death.' The army was shocked. They could not understand why Ram would honor the man who had caused him so much pain. But Ram understood something they did not. He understood that carrying anger and hatred is like drinking poison and expecting the other person to die. He refused to carry that poison. He forgave everyone. He forgave Kaikeyi, who had exiled him. He forgave Sita, who had trusted the golden deer. He forgave Vibhishana's brother, who had fought against him. He forgave Ravana. He let go of every grudge. He refused to let the past destroy his future.",
        hi: "युद्ध समाप्त हो गया था। रावण युद्धभूमि में पराजित पड़ा था। राम जीत गए थे। उन्हें अपनी पत्नी वापस मिल गई थी। उन्हें अपना सम्मान वापस मिल गया था। उनके पास वह सब कुछ था जिसके लिए उन्होंने लड़ाई लड़ी थी। और फिर, उन्होंने कुछ ऐसा किया जो किसी ने उम्मीद नहीं की थी। उन्होंने हनुमान से रावण का शरीर लाने को कहा। उन्होंने आदेश दिया कि रावण को उचित अंतिम संस्कार दिया जाए। उन्होंने कहा, 'वह एक महान विद्वान थे। वह एक महान राजा थे। उन्होंने भयानक विकल्प चुने, लेकिन वह एक बुरे व्यक्ति नहीं थे। वह मेरे दुश्मन थे, लेकिन वह एक ब्राह्मण, एक विद्वान और शिव के भक्त भी थे। मृत्यु में वह सम्मान के पात्र हैं।' सेना सदमे में थी। वे नहीं समझ सकते थे कि राम उस व्यक्ति का सम्मान क्यों करेंगे जिसने उन्हें इतना दर्द दिया था। लेकिन राम कुछ समझते थे जो वे नहीं समझते थे। वह समझते थे कि क्रोध और घृणा को धारण करना जहर पीने और दूसरे व्यक्ति के मरने की उम्मीद करने जैसा है। उन्होंने वह जहर धारण करने से इनकार कर दिया। उन्होंने सभी को क्षमा कर दिया। उन्होंने कैकेयी को क्षमा किया, जिसने उन्हें निर्वासित किया था। उन्होंने सीता को क्षमा किया, जिन्होंने सुनहले हिरण पर विश्वास किया था। उन्होंने विभीषण के भाई को क्षमा किया, जिसने उनके खिलाफ लड़ाई लड़ी थी। उन्होंने रावण को क्षमा किया। उन्होंने हर द्वेष को छोड़ दिया। उन्होंने अतीत को अपना भविष्य नष्ट करने से इनकार कर दिया।",
        sa: "युद्धम् समाप्तम्। रावणः युद्धभूमौ पराजितः पतितः। रामः विजयी। तस्य पत्नी पुनः प्राप्ता। तस्य गौरवम् पुनः प्राप्तम्। तस्य सर्वम् यत् सः युद्धितवान्। तदा, सः किमपि अकरोत् यत् न कोऽपि अमन्यत। सः हनुमन्तम् रावणस्य शरीरम् आनेतुम् अकथयत्। सः आज्ञापयत् यत् रावणाय उचितम् अन्त्यसंस्कारम् कुर्वन्तु। सः अवदत्, 'सः महान् पण्डितः। सः महान् राजा। सः भयानकानि विकल्पानि अचिनोत्, किन्तु सः दुष्टः न आसीत्। सः मम शत्रुः आसीत्, किन्तु सः ब्राह्मणः, पण्डितः, शिवभक्तः च आसीत्। मृत्यौ सः सम्मानम् अर्हति।' सेना स्तब्धा आसीत्। ते न अबुध्यन्त यत् रामः तम् सम्मानयति यः तस्मै अतीव दुःखम् अददात्। किन्तु रामः किमपि अबुध्यत यत् ते न अबुध्यन्त। सः अबुध्यत यत् क्रोधम् द्वेषम् च धारयितुम् विषम् पातुम् इव, अन्यस्य मरणम् आशास्य। सः तत् विषम् धारयितुम् न अइच्छत्। सः सर्वान् क्षमितवान्। सः कैकेयीम् क्षमितवान्, या तम् निर्वासितवती। सः सीताम् क्षमितवान्, या सुवर्णमृगे विश्वस्तवती। सः विभीषणस्य भ्रातारम् क्षमितवान्, यः तस्य विरुद्धम् अयुध्यत। सः रावणम् क्षमितवान्। सः सर्वम् द्वेषम् अत्यजत्। सः अतीतम् तस्य भविष्यम् नाशयितुम् न अइच्छत्।",
        question: "Who in your life do you need to forgive? What grudge are you carrying that is only weighing you down?",
        answer: "Ram had every right to be angry. He had lost years of his life in the forest. He had lost his father. He had fought a brutal war. He had seen his wife kidnapped and humiliated. But he chose forgiveness over bitterness. He understood that carrying anger and hatred is like drinking poison and expecting the other person to die. He let go. He freed himself.",
        takeaway: "Forgiveness is not about them. It is about you. It is the act of freeing yourself from the prison of resentment. Forgive, not because they deserve it, but because you deserve peace. Holding onto anger is heavy. Set it down and walk free."
    },

    // ============================================================
    // CHAPTER 12: Uttara Kanda - The King Within
    // ============================================================
    {
        id: 12,
        title: "Uttara Kanda - The King Within",
        image: "ramayan-images/king-ram.jpg",
        setting: "What does true leadership look like? Is it about commanding others, or is it about serving them? When you finally have power, do you use it to lift people up or to push them down?",
        en: "Ram returned to Ayodhya. The city that had wept when he left now erupted in celebration. Flowers rained from every window. The streets were filled with music and dancing. He was crowned king, and the people rejoiced. But Ram did not see himself as a ruler; he saw himself as a servant. He sat on the throne, but he never forgot that he was there to serve the people. He listened to every citizen who came to him. He solved their problems personally. He woke up before the sun and worked until after the stars appeared. He never asked anyone to do something he would not do himself. He treated the poorest farmer with the same respect he showed the wealthiest merchant. He ruled with kindness, not with fear. He ruled with justice, not with favoritism. He ruled with humility, not with arrogance. His kingdom prospered. There was no hunger, no crime, no fear. The people loved him because he was kind, not because he was powerful. He proved that true power is not about commanding others; it is about serving them. He proved that the greatest king is not the one who rules over the most people, but the one who loves them the most.",
        hi: "राम अयोध्या लौटे। जिस नगरी ने उनके जाने पर आँसू बहाए थे, अब वह जश्न में फूट पड़ी। हर खिड़की से फूल बरस रहे थे। सड़कें संगीत और नृत्य से भर गईं। उन्हें राजा का ताज पहनाया गया, और लोग खुशी से झूम उठे। लेकिन राम ने खुद को शासक के रूप में नहीं देखा; उन्होंने खुद को एक सेवक के रूप में देखा। वह सिंहासन पर बैठे, लेकिन उन्होंने कभी नहीं भूला कि वह लोगों की सेवा करने के लिए वहाँ थे। उन्होंने हर उस नागरिक की बात सुनी जो उनके पास आया। उन्होंने उनकी समस्याओं को व्यक्तिगत रूप से हल किया। वह सूरज से पहले उठते और तारे दिखने के बाद तक काम करते। उन्होंने कभी किसी से कुछ ऐसा करने को नहीं कहा जो वे स्वयं नहीं करते थे। उन्होंने सबसे गरीब किसान के साथ उसी सम्मान से पेश आया जिस सम्मान से वह सबसे अमीर व्यापारी के साथ पेश आते थे। उन्होंने दया से शासन किया, भय से नहीं। उन्होंने न्याय से शासन किया, पक्षपात से नहीं। उन्होंने विनम्रता से शासन किया, अहंकार से नहीं। उनका राज्य समृद्ध हुआ। वहाँ कोई भूख नहीं थी, कोई अपराध नहीं था, कोई भय नहीं था। लोग उनसे प्यार करते थे क्योंकि वह दयालु थे, इसलिए नहीं कि वह शक्तिशाली थे। उन्होंने साबित किया कि सच्ची शक्ति दूसरों को आदेश देने में नहीं है; यह उनकी सेवा करने में है। उन्होंने साबित किया कि सबसे महान राजा वह नहीं है जो सबसे अधिक लोगों पर शासन करता है, बल्कि वह है जो उनसे सबसे अधिक प्रेम करता है।",
        sa: "रामः अयोध्याम् प्रत्यागतः। या नगरी तस्य गमने अरोदीत्, सा अद्य उत्सवेन उद्धृता। प्रत्येकस्मात् गवाक्षात् पुष्पाणि वर्षन्ति स्म। मार्गाः सङ्गीतेन नृत्येन च पूर्णाः। सः राजा अभिषिक्तः, जनाः आनन्दिताः। किन्तु रामः स्वयम् शासकम् न अपश्यत्; सः स्वयम् सेवकम् अपश्यत्। सः सिंहासने उपविष्टः, किन्तु न विस्मृतवान् यत् सः जनानाम् सेवायै तत्र आसीत्। सः प्रत्येकम् नागरिकम् अशृणोत् यः तम् आगच्छत्। सः तेषाम् समस्याः स्वयम् असुलयत्। सः सूर्यात् पूर्वम् उत्थितवान्, तारकाः दृश्यन्ते यावत् कार्यम् अकरोत्। सः कदापि कस्मैचित् न अकथयत् यत् सः स्वयम् न करोति। सः निर्धनतमम् कृषकम् तेनैव आदरेण अमन्यत येन धनिनम् वणिजम्। सः दयया अशास्त, भयेन न। सः न्यायेन अशास्त, पक्षपातेन न। सः विनम्रतया अशास्त, अहङ्कारेण न। तस्य राज्यम् समृद्धम् अभवत्। न क्षुत्, न अपराधः, न भयम्। जनाः तम् अप्रियन् यतः सः दयालुः, न यतः सः बलवान्। सः अप्रमाणयत् यत् सत्यम् बलम् परान् आज्ञापयितुम् न, अपितु तेषाम् सेवयितुम्। सः अप्रमाणयत् यत् महान् राजा न यः अधिकान् जनान् शास्ति, अपितु यः तान् अधिकम् प्रियति।",
        question: "Are you leading your life like a king or like a servant? Are you focused on power, or on purpose?",
        answer: "Ram had absolute power. He was the king of the greatest kingdom on earth. He could have done anything he wanted. He could have lived in luxury. He could have ignored the poor. He could have ruled with an iron fist. He chose not to. He remained humble, approachable, and kind. He understood that true leadership is not about being served; it is about serving. He understood that power is not a privilege; it is a responsibility.",
        takeaway: "You are the king or queen of your own life. But that does not mean you rule others. It means you take responsibility for yourself and for those around you. Lead with kindness. Serve with humility. Love without condition. That is how you build a kingdom worth ruling."
    }
];

// ============================================================
// HELPER FUNCTIONS
// ============================================================

function getStoryData() {
    return storyData;
}

function getChapter(index) {
    return storyData[index] || null;
}

function getTotalChapters() {
    return storyData.length;
}

// ============================================================
// CREDIT AND PURPOSE
// ============================================================
console.log("========================================");
console.log("RAMAYANA - Eternal Wisdom for Modern Life");
console.log("Created by Varaang Sharma");
console.log("Contact: varaangsharma@gmail.com");
console.log("========================================");
console.log("Purpose: To make the timeless wisdom of");
console.log("Ramayana accessible to modern readers and");
console.log("help them find motivation in their daily");
console.log("lives. This website is a free resource");
console.log("dedicated to spreading positivity and");
console.log("strength through the story of Ram.");
console.log("========================================");